config/routes.rb
Joexpo::Application.routes.draw do
  root :to => 'expos#index'
  resources :expos

end

app/models/expo.rb
class Expo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/expos_controller.rb
# encoding: utf-8

class ExposController < ApplicationController
  respond_to :html
  expose(:expos) { Expo.all }
  expose(:expo) { params[:id].present? ? Expo.find(params[:id]) : Expo.last }

  def index
    render :action => 'show'
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    flash[:notice] = 'Tenemos nueva colección.' if expo.save
    respond_with expo, :location => expo
  end

  def update
    flash[:notice] = 'Colección modificada.' if expo.update_attributes(params[:expo])
    respond_with expo, :location => expo
  end

  def destroy
    flash[:notice] = 'Colección borrada.' if expo.destroy
    respond_with expo, :location => expos_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expos_helper.rb
module ExposHelper
end

app/views/expos/_form.html.erb
<%= form_for(@expo) do |f| %>
  <% if @expo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expo.errors.count, "error") %> prohibited this expo from being saved:</h2>

      <ul>
      <% @expo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :background_color %><br />
    <%= f.text_field :background_color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expos/edit.html.erb
<h1>Editing expo</h1>

<%= render 'form' %>

<%= link_to 'Show', @expo %> |
<%= link_to 'Back', expos_path %>

app/views/expos/index.html.erb
<h1>Listing expos</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Background color</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @expos.each do |expo| %>
  <tr>
    <td><%= expo.name %></td>
    <td><%= expo.background_color %></td>
    <td><%= link_to 'Show', expo %></td>
    <td><%= link_to 'Edit', edit_expo_path(expo) %></td>
    <td><%= link_to 'Destroy', expo, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Expo', new_expo_path %>

app/views/expos/new.html.erb
<h1>New expo</h1>

<%= render 'form' %>

<%= link_to 'Back', expos_path %>

app/views/expos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @expo.name %>
</p>

<p>
  <b>Background color:</b>
  <%= @expo.background_color %>
</p>


<%= link_to 'Edit', edit_expo_path(@expo) %> |
<%= link_to 'Back', expos_path %>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lte IE 8 ]>
<html lang="en" class="no-js oldie"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en" class="no-js"> <!--<![endif]-->
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title><%= yield :title %> - Jo Expósito</title>
  <meta name="description" content="Jose Expósito showcase">
  <meta name="author" content="joexposito,danigb,recortable.net">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="shortcut icon" href="/favicon.ico">
  <script src="/javascripts/libs/modernizr-1.7.min.js"></script>
</head>
<body>
<div id="container">
  <header>

  </header>

  <div id="main" role="main">
    <%= yield %>
  </div>
  <footer>
  </footer>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
<script>!window.jQuery && document.write(unescape('%3Cscript src="js/libs/jquery-1.5.1.min.js"%3E%3C/script%3E'))</script>
<script src="js/plugins.js"></script>
<script src="js/script.js"></script>
<script>
    var _gaq = [
        ['_setAccount','UA-XXXXX-X'],
        ['_trackPageview']
    ]; // Change UA-XXXXX-X to be your site's ID
    (function(d, t) {
        var g = d.createElement(t),s = d.getElementsByTagName(t)[0];
        g.async = 1;
        g.src = ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js';
        s.parentNode.insertBefore(g, s)
    }(document, 'script'));
</script>
</body>
</html>